# formurae
brew "bat"
brew "ruby"
brew "curl"
brew "ffmpeg"
brew "gh"
brew "git"
brew "julia"
brew "liblzf"
brew "lsd"
brew "neovim"
brew "nodenv"
brew "opam"
brew "pandoc"
brew "pandoc-crossref"
brew "pandoc-plot"
brew "pdfpc"
brew "pyenv"
brew "r"
brew "rbenv"
brew "rust"
brew "sevenzip"
brew "sheldon"
brew "smartmontools"
brew "speedtest-cli"
brew "tree"
brew "tsduck"
brew "zsh"
brew "htrb/tap/ngraph-gtk"
brew "zegervdv/zathura/girara", args: ["HEAD"]
brew "zegervdv/zathura/zathura", args: ["HEAD"]
brew "zegervdv/zathura/zathura-pdf-poppler"
brew "mas"

# tap
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "htrb/tap"
tap "zegervdv/zathura"
tap "mas-cli/tap"

# fonts
brew "meslo-lg-nerd-font"

# casks
cask "alfred"
cask "apparency"
cask "balenaetcher"
cask "brave-browser"
cask "cleanmymac"
cask "deepl"
cask "fliqlo"
cask "font-inconsolata"
cask "font-meslo-lg-nerd-font"
cask "github"
cask "google-drive"
cask "google-japanese-ime"
cask "iina"
cask "iterm2"
cask "keyboard-cleaner"
cask "kindle"
cask "latexit"
cask "mactex-no-gui"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-teams"
cask "microsoft-word"
cask "notion"
cask "numi"
cask "onedrive"
cask "readdle-spark"
cask "rstudio"
cask "skim"
cask "slidepilot"
cask "steam"
cask "tex-live-utility"
cask "the-unarchiver"
cask "tunnelblick"
cask "visual-studio-code"
cask "vlc"
cask "webex"
cask "xquartz"
cask "zoom"

# mas
mas "line", id: 539883307
mas "Twitter", id: 409789998
mas "todoist", id: 585829637
mas "dictonaly", id: 1380563956
mas "Kindle", id: 405399194
mas "duckduckgo_safari", id: 1480068668
